version: '3'

# Deploying services

services:

# Elastic cluster to store data
  elasticsearch:
    image: elasticsearch:7.17.0
    
    volumes:
      - type: bind
        source: "./elasticsearch/config/elasticsearch.yml"
        target: "/usr/share/elasticsearch/config/elasticsearch.yml"
        read_only: true
      - type: volume
        source: elasticsearch
        target: "/usr/share/elasticsearch/data"
    ports:
      -  "9200:9200"
      -  "9300:9300"
    environment:
      ELASTIC_USER: elastic
      ELASTIC_PASSWORD: changeme%
    networks:
      - elk
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000"
      - "9600:9600"
    expose: 
      - "5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
     
# Deploying kibana   
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
      
# Setting up nginx to map it's logs
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - 
    depends_on: 
      - 
    networks:
      - elk
   
# Get data from kibana
  
  filebeat:
    build: ./filebeat
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./nginx/log:/var/log/nginx
    networks:
      - elk
    depends_on: 
      - nginx
      - elasticsearch
      - kibana
      -logstash
    links: 
      - logstash

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:

